name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: make build

    - name: Test
      run: make test

  push:
    runs-on: ubuntu-20.04
    if: ${{ github.GITHUB_EVENT_NAME == "push" }}
    steps:
      - run: echo "Check is working"